name: PR
on:
  pull_request:
    paths:
      - ".github/workflows/pr.yml"
      - "oop/**"
concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: true
jobs:
  backend_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: oop
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: "18.19.1"

      - name: Get npm cache directory path
        id: npm-cache-dir-path
        run: echo "{name}=dir::$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: |
            ./node_modules
            ${{ steps.npm-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-npm-${{ hashFiles('./oop/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm

      - name: Install application dependencies
        run: npm install

      - name: Run tests
        run: npm test --ci
